### ISSUE TITLE
Automatically pull weather data

### ISSUE THREAD

**Issue by praftery** [CenterForTheBuiltEnvironment/mave#9]
... based on ZIP code using an API:

http://www.wunderground.com/weather/api/d/docs?d=index
or
http://www.ncdc.noaa.gov/cdo-web/webservices/v2#stations

**Comment by praftery** [comment]
@taoning 
Outstanding issues:
1) Datetimes are not correctly synchronized - self.target_unix and self.unix are off by a significant number of hours (probably due to a timezone issue somewhere)
2) only works for ranges starting and ending at datetimes that are the interp_interval divides evenly into an hour. e.g. start= 2011/1/1 01:00 and interp_interval = 15m works fine, but it fails if you start with 2011/1/1 01:03

**Comment by praftery** [comment]
Also, the api method does not seem to work...

**Comment by taoning** [comment]
All is working except issue number 2.

**Comment by praftery** [comment]
So numpy arange functionality doesn't do what we want, but we need the datetimes to match up exactly to the other data. One way is to compute the timedelta error between the output of the arange function and the start date, and add that timedelta to all of the arange values. Then you'd just need to remove the datetimes > end and it should match...

**Comment by praftery** [comment]
@taoning 
note that the committed version fails the unittests - a forgotten pdb.set_trace()
Also, the target_dt array needs to be trimmed so that it ends on the end date...
